name: Django CI

# on:
#   push:
#     branches-ignore:
#       # Do not push events to branches matching refs/heads/mona/octocat
#       - 'Normal'
#   pull_request:
#     branches-ignore:
#       # Do not push events to branches matching refs/heads/mona/octocat
#       - 'Normal'

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on main branch
      - main
      # Push events to branches matching refs/heads/mona/octocat
      - Normal
      # Push events to branches matching refs/heads/releases/10

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run Tests
      run: |
        python test.py
